### ISSUE TITLE
Only timepicker init

### ISSUE THREAD

**Issue by Sunsvision** [PitPik/tinyDatePicker#2]
Hello!
Is it possible to use timepicker only when there are no init value in the input? 
Unfortunately I did not find info about such option. 
Thanks for the great plugin!

**Comment by PitPik** [comment]
Hi @Sunsvision ,
thanks for your interest in date/time picker :)
Unfortunately there is no support yet, you need to start with a time format and time picker picks is up.
I definitely see the need for this, so I will implement something as soon as possible (probably an attribute on the input field as fallback...)
So please be patient, I will get my fingers on it ;o)
Cheers
Peter

**Comment by PitPik** [comment]
Hi @Sunsvision ,
for now I do have a solution for you:
If you don't mind that the input field gets filled the first time it get clicked/focused then just add the option:
```javascript
readValue: function(element) {
    if (!element.value) { // initial time if empty
        element.value = new Date().toTimeString().split(' ')[0];
    }

    return element.value; // triggers default behavior
}
```
otherwhise use a hidden input field like:
```HTML
<input class="date" data-helper="time-only" value="" />
<input id="time-only" type="hidden" value="" />
```
where the ```data-helper``` attribute has the name of the hidden input's id and use the following options:
```javascript
window.myDatePicker = new DatePicker('.date', {
    renderValue: function(container, element, value) {
        var helper = document.getElementById(element.getAttribute('data-helper'));

        helper.value = value;
        return element; // triggers default behavior on certain element
    },
    readValue: function(element) {
        var helper = document.getElementById(element.getAttribute('data-helper'));

        if (!helper.value) { // initial time if empty
            helper.value = new Date().toTimeString().split(' ')[0];
        }

        return helper.value; // triggers default behavior
    }
}
```

**Comment by PitPik** [comment]
Hi @Sunsvision ,
thanks for your interest in date/time picker :) (and sorry for the mail flood while cleaning up comments).

Unfortunately there is no built in option but with the following instructions this is easily possible:

Just make your own `data-type` attribute:

``` HTML
<input class="date" value="" data-type="time" />
```

and use the following options:

``` javascript
window.myDatePicker = new DatePicker('.date', {
    readValue: function(element) {
        if (!element.value && element.getAttribute('data-type') === 'time') {
            return new Date().toTimeString().split(' ')[0]; // triggers default behavior
        }

        return element.value; // triggers default behavior
    }
};
```

You probably see that with this technique you're quite flexible in what you want to do. You can also make your own rules for how to pick up formats...

**Comment by Sunsvision** [comment]
Elegant solution, thanks a lot!
