### ISSUE TITLE
Safari - minDate

### ISSUE THREAD

**Issue by cwffm** [PitPik/tinyDatePicker#4]
Hi,
is **minDate** also working in Safari?
In your demo and in my application it is not working like it is in the other browser.

Christian

**Comment by PitPik** [comment]
Hi @cwffm ,
well, thanks for this finding. Seems as if Date.parse() doesn't work as expected in Safari or better, as in other browsers. So the bug sits in _convertDateString() inside calendar.js
I will try to fix this as soon as possible.
Cheers

**Comment by PitPik** [comment]
Hi @cwffm again,
the bug is fixed... please let me know if this works now for you

**Comment by cwffm** [comment]
Hi,
is working good.

Thanks
