### ISSUE TITLE
Changing Week Number (WeekNo)

### ISSUE THREAD

**Issue by macedits** [PitPik/tinyDatePicker#5]
Being new to Javascript I may have missed this but is there a way to change where Week Numbers (WeekNo) start like Week One = January 14? My use case would be to count university weeks in a semester. I saw the WeekNo variable but I must not be using it right....

**Comment by PitPik** [comment]
Hi @macedits ,
well, printing standard week days has nothing to do with JS... and there is a standard called ISO 8601 that describes how to print dates and also describes how to calculate week days. So, I didn't consider to change this or make it optional...
Other than that, this date picker is flexible enough to show your own things (not only University weeks) when it's rendering. This can be done in the ```renderCallback()``` where you get the container the calendar sits in and you can add more stuff you need...
The ```weekNo``` variable is inside ```template``` and just describes a template part for rendering week days.
