### ISSUE TITLE
Using 24 hours time gives too many hours

### ISSUE THREAD

**Issue by bgiaccio** [PitPik/tinyDatePicker#8]
When using 24 hour time format the drop down shows 0 - 24  meaning I can select 24:30 as a time.
Trying to turn that into a date object will fail.  The drop down should stop at 23

I believe you want to change line 288 of datePicker.js to be 23 vice 24.

**Comment by PitPik** [comment]
Hey @bgiaccio ,
thanks for this finding (and sorry for the late response).
I just updated.
Cheers

**Comment by umbundu** [comment]
If you have a datepicker on the page body, it works fine. If you have it inside a tab control nothing happens.
